[package]
name = "implicit3d"
version = "0.7.0"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[lib]
name = "implicit3d"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.14"
alga = "0.5"
stl_io = "0.3"
bbox = "0.7"
num-traits = "0.2"

[dev-dependencies]
bencher = "0.1.*"
approx = "0.1"

[[bench]]
name = "objects"
path = "src/benches/objects.rs"
harness = false
